GET http://localhost:3000/health

###
POST http://localhost:3000/api/auth/sign-up
Accept: application/json
Content-Type: application/json

{
  "name": "mferdy",
  "email": "mferdy@example.com",
  "password": "123456"
}

###
POST http://localhost:3000/api/auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "email": "ferdy@example.com",
  "password": "123456"
}

###
POST http://localhost:3000/api/auth/sign-out
Accept: application/json
Content-Type: application/json
